USE [LDVP]
GO

/****** Object:  Table [dbo].[Snack]    Script Date: 2021-11-13 12:09:06 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [ldvp].[Snack](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[Nom] [nvarchar](max) NULL,
 CONSTRAINT [PK_Snack] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
